### ISSUE TITLE
Code recurrence problem

### ISSUE THREAD

**Issue by XLLXO** [hailanyi/TED#22]
Hello, author
I had a problem replicating your code.
I used two 3090 video cards with batch_size set to 4 and epochs set to 80.
After training, the 3D AP(R40) of Car on the val set of KITTI dataset was only 92.07, 85.49, 84.95, which was two points behind the 93.25, 87.99, 86.28 published by your github.
I would like to ask you, what is the cause of this?
![001](https://user-images.githubusercontent.com/101243361/233064322-0155f43b-6a61-43e4-a49d-edb0d8370201.png)
![002](https://user-images.githubusercontent.com/101243361/233064565-ce0583ee-ddd9-45b8-b39a-1ad507f22569.png)

**Comment by hailanyi** [comment]
Sometimes the training is not every stable. Please try: 1 Train several times. 2 Using a low score threshold.

```
    POST_PROCESSING:
        RECALL_THRESH_LIST: [0.3, 0.5, 0.7]
        SCORE_THRESH: 0.7  # please try 0.6, 0.5, 0.4, 0.3
        OUTPUT_RAW_SCORE: False
        EVAL_METRIC: kitti
```
